baseURL = "https://zielonacerekiew.pl"
disqusShortname = ""
googleAnalytics = ""
paginate = "10"
summaryLength = "20"
theme = "apollo-hugo"
title = "Stowarzyszenie Zielona Cerekiew"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "O nas"
url = "About"
weight = "1"
[[menu.main]]
name = "Statut"
url = "elements"
weight = 2
[[menu.main]]
name = "Nasze Cele"
url = "terms-conditions"
weight = 3
[[menu.main]]
name = "Kontakt"
url = "contact"
weight = 4
[outputs]
home = ["HTML", "RSS"]
[params]
author = "Cgorka"
banner_content = "Jesteśmy grupą osób, które chcą pozytywnego, pozbawionego waśni, sporów miejsca w którym żujemy. Pracujemy na rzecz społeczności lokalnej, naszych sąsiadów i mieszkańców."
copyright = "ZielonaCerekiew.pl"
custom_script = ""
description = "Zielona Cerekiew"
favicon = "images/favicon.png"
logo = "images/logo-via-logohub-1.png"
logo_width = "200px"
main_section = "about"
[params.cookies]
enable = false
expire_days = 2
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
[params.variables]
black = "#000"
body_color = "#fff"
border_color = "#e2e2e2"
icon_font = "Fontawesome 5 Free"
light = "#f1f1f1"
primary_color = "#33186D"
primary_font = "DM Sans:400,500,700"
text_color = "#333"
text_color_dark = "#000"
text_color_light = "#999"
white = "#fff"
[[params.social]]
icon = "fab fa-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "fab fa-instagram"
link = "#"
title = "instagram"
